In [84]:
import numpy as np 
import pandas as pd 
import matplotlib 
import matplotlib.pyplot as plt

In [85]:
space_data = pd.read_csv('C:\\Users\\HP\\Documents\\spaceProject\\train.csv')
space_data.tail()

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
8688,9276_01,Europa,False,A/98/P,55 Cancri e,41.0,True,0.0,6819.0,0.0,1643.0,74.0,Gravior Noxnuther,False
8689,9278_01,Earth,True,G/1499/S,PSO J318.5-22,18.0,False,0.0,0.0,0.0,0.0,0.0,Kurta Mondalley,False
8690,9279_01,Earth,False,G/1500/S,TRAPPIST-1e,26.0,False,0.0,0.0,1872.0,1.0,0.0,Fayey Connon,True
8691,9280_01,Europa,False,E/608/S,55 Cancri e,32.0,False,0.0,1049.0,0.0,353.0,3235.0,Celeon Hontichre,False
8692,9280_02,Europa,False,E/608/S,TRAPPIST-1e,44.0,False,126.0,4688.0,0.0,0.0,12.0,Propsh Hontichre,True

In [86]:
space_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8693 entries, 0 to 8692
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   PassengerId   8693 non-null   object
 1   HomePlanet    8492 non-null   object
 2   CryoSleep     8476 non-null   object
 3   Cabin         8494 non-null   object
 4   Destination   8511 non-null   object
 5   Age           8514 non-null   float64
 6   VIP           8490 non-null   object
 7   RoomService   8512 non-null   float64
 8   FoodCourt     8510 non-null   float64
 9   ShoppingMall  8485 non-null   float64
 10  Spa           8510 non-null   float64
 11  VRDeck        8505 non-null   float64
 12  Name          8493 non-null   object
 13  Transported   8693 non-null   bool
dtypes: bool(1), float64(6), object(7)
memory usage: 891.5+ KB

In [87]:
space_data = space_data.dropna(subset=['Name'])
space_data.info()
# cleaning = cleaning.dropna(subset=['MasVnrType', 'Electrical'])

<class 'pandas.core.frame.DataFrame'>
Index: 8493 entries, 0 to 8692
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   PassengerId   8493 non-null   object
 1   HomePlanet    8299 non-null   object
 2   CryoSleep     8286 non-null   object
 3   Cabin         8296 non-null   object
 4   Destination   8315 non-null   object
 5   Age           8317 non-null   float64
 6   VIP           8291 non-null   object
 7   RoomService   8313 non-null   float64
 8   FoodCourt     8315 non-null   float64
 9   ShoppingMall  8289 non-null   float64
 10  Spa           8316 non-null   float64
 11  VRDeck        8309 non-null   float64
 12  Name          8493 non-null   object
 13  Transported   8493 non-null   bool
dtypes: bool(1), float64(6), object(7)
memory usage: 937.2+ KB

In [88]:
my_space=space_data[['RoomService', 'FoodCourt', 'ShoppingMall', 'Spa', 'VRDeck']].fillna(0, axis=0)
my_space.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8493 entries, 0 to 8692
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   RoomService   8493 non-null   float64
 1   FoodCourt     8493 non-null   float64
 2   ShoppingMall  8493 non-null   float64
 3   Spa           8493 non-null   float64
 4   VRDeck        8493 non-null   float64
dtypes: float64(5)
memory usage: 398.1 KB

In [89]:
space_data[['RoomService', 'FoodCourt', 'ShoppingMall', 'Spa', 'VRDeck']] = my_space

In [90]:
space_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8493 entries, 0 to 8692
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   PassengerId   8493 non-null   object
 1   HomePlanet    8299 non-null   object
 2   CryoSleep     8286 non-null   object
 3   Cabin         8296 non-null   object
 4   Destination   8315 non-null   object
 5   Age           8317 non-null   float64
 6   VIP           8291 non-null   object
 7   RoomService   8493 non-null   float64
 8   FoodCourt     8493 non-null   float64
 9   ShoppingMall  8493 non-null   float64
 10  Spa           8493 non-null   float64
 11  VRDeck        8493 non-null   float64
 12  Name          8493 non-null   object
 13  Transported   8493 non-null   bool
dtypes: bool(1), float64(6), object(7)
memory usage: 937.2+ KB

In [91]:
space_data['CryoSleep'].fillna(False, inplace=True)
space_data['VIP'].fillna(True, inplace=True)

In [92]:
halffilled_data = space_data[['HomePlanet', 'Destination']].fillna(method='bfill')
filled_data = space_data['Cabin'].fillna(method='ffill')
space_data[['HomePlanet', 'Destination']] = halffilled_data
space_data['Cabin'] = filled_data

In [93]:
space_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8493 entries, 0 to 8692
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   PassengerId   8493 non-null   object
 1   HomePlanet    8493 non-null   object
 2   CryoSleep     8493 non-null   bool
 3   Cabin         8493 non-null   object
 4   Destination   8493 non-null   object
 5   Age           8317 non-null   float64
 6   VIP           8493 non-null   bool
 7   RoomService   8493 non-null   float64
 8   FoodCourt     8493 non-null   float64
 9   ShoppingMall  8493 non-null   float64
 10  Spa           8493 non-null   float64
 11  VRDeck        8493 non-null   float64
 12  Name          8493 non-null   object
 13  Transported   8493 non-null   bool
dtypes: bool(3), float64(6), object(5)
memory usage: 821.1+ KB

In [94]:
space_data = space_data.dropna(subset=['Age'])
space_data.reset_index(drop=True, inplace=True)

In [95]:
space_data.tail()

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
8312,9276_01,Europa,False,A/98/P,55 Cancri e,41.0,True,0.0,6819.0,0.0,1643.0,74.0,Gravior Noxnuther,False
8313,9278_01,Earth,True,G/1499/S,PSO J318.5-22,18.0,False,0.0,0.0,0.0,0.0,0.0,Kurta Mondalley,False
8314,9279_01,Earth,False,G/1500/S,TRAPPIST-1e,26.0,False,0.0,0.0,1872.0,1.0,0.0,Fayey Connon,True
8315,9280_01,Europa,False,E/608/S,55 Cancri e,32.0,False,0.0,1049.0,0.0,353.0,3235.0,Celeon Hontichre,False
8316,9280_02,Europa,False,E/608/S,TRAPPIST-1e,44.0,False,126.0,4688.0,0.0,0.0,12.0,Propsh Hontichre,True

In [96]:
# space_data = space_data.drop(['Name', 'PassengerId'], axis=1)
space_data.tail()

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
8267,9220_03,Earth,False,F/1886/P,PSO J318.5-22,22.0,False,623.0,0.0,0.0,0.0,53.0,Kennie Barrilloney,True
8268,9221_01,Earth,True,G/1497/P,TRAPPIST-1e,21.0,False,0.0,0.0,0.0,0.0,0.0,Elicey Beachez,False
8269,9222_01,Mars,True,F/1784/S,TRAPPIST-1e,50.0,False,0.0,0.0,0.0,0.0,0.0,Carves Chate,True
8270,9224_01,Mars,False,F/1786/S,TRAPPIST-1e,24.0,False,745.0,639.0,977.0,4.0,0.0,Bants Reke,False
8271,9225_01,Earth,False,F/1787/S,TRAPPIST-1e,45.0,False,1.0,197.0,0.0,660.0,15.0,Lynnon Meyersones,False
8272,9226_01,Earth,False,F/1788/S,TRAPPIST-1e,22.0,False,676.0,0.0,13.0,0.0,12.0,Stendy Connelson,False
8273,9227_01,Earth,True,G/1498/P,TRAPPIST-1e,7.0,False,0.0,0.0,0.0,0.0,0.0,Glendy Hinglendez,False
8274,9227_02,Earth,True,G/1498/P,PSO J318.5-22,11.0,False,0.0,0.0,0.0,0.0,0.0,Jorgie Hinglendez,True
8275,9227_03,Earth,True,G/1498/P,PSO J318.5-22,1.0,False,0.0,0.0,0.0,0.0,0.0,Paulas Hinglendez,True
8276,9227_04,Earth,True,G/1498/P,TRAPPIST-1e,0.0,False,0.0,0.0,0.0,0.0,0.0,Robyny Hinglendez,True
8277,9227_05,Earth,False,G/1498/P,TRAPPIST-1e,8.0,False,0.0,0.0,0.0,0.0,0.0,Hard Hinglendez,False
8278,9231_01,Mars,True,F/1888/P,55 Cancri e,2.0,False,0.0,0.0,0.0,0.0,0.0,Denuts Paie,True
8279,9231_02,Mars,False,F/1888/P,TRAPPIST-1e,0.0,False,0.0,0.0,0.0,0.0,0.0,Walls Paie,True
8280,9231_03,Mars,False,E/592/P,TRAPPIST-1e,22.0,False,0.0,0.0,0.0,0.0,0.0,Cus Paie,False
8281,9233_01,Earth,False,E/592/P,TRAPPIST-1e,41.0,False,3.0,0.0,668.0,0.0,0.0,Royce Giller,True
8282,9234_01,Earth,False,G/1500/P,TRAPPIST-1e,49.0,False,6.0,1.0,638.0,1107.0,23.0,Catha Bushins,False
8283,9235_01,Earth,False,F/1789/S,TRAPPIST-1e,30.0,False,8.0,752.0,0.0,0.0,687.0,Joanny Burchrison,True
8284,9237_01,Earth,True,G/1488/S,TRAPPIST-1e,37.0,False,0.0,0.0,0.0,0.0,0.0,Philda Floways,False
8285,9239_01,Mars,False,E/593/P,TRAPPIST-1e,14.0,False,2.0,0.0,918.0,128.0,0.0,Per Minen,False
8286,9241_01,Mars,False,E/595/P,TRAPPIST-1e,30.0,False,699.0,0.0,600.0,0.0,0.0,Ants Fone,False
8287,9242_01,Earth,False,F/1891/P,TRAPPIST-1e,62.0,False,102.0,696.0,0.0,0.0,0.0,Dary Bakerrison,True
8288,9244_01,Earth,True,G/1489/S,PSO J318.5-22,13.0,False,0.0,0.0,0.0,0.0,0.0,Chrisa Francock,True
8289,9247_01,Earth,True,G/1491/S,TRAPPIST-1e,33.0,False,0.0,0.0,0.0,0.0,0.0,Phia Cleang,False
8290,9248_01,Europa,False,F/1792/S,55 Cancri e,38.0,True,28.0,1208.0,973.0,207.0,0.0,Gian Perle,True
8291,9250_01,Europa,False,E/597/P,TRAPPIST-1e,29.0,False,0.0,2972.0,0.0,28.0,188.0,Chain Reedectied,True
8292,9251_01,Mars,True,F/1793/S,TRAPPIST-1e,25.0,False,0.0,0.0,0.0,0.0,0.0,Melios Kashe,True
8293,9252_01,Europa,False,B/301/P,55 Cancri e,26.0,False,0.0,8160.0,205.0,0.0,438.0,Alchium Stranbeate,True
8294,9252_02,Europa,True,B/301/P,55 Cancri e,19.0,False,0.0,0.0,0.0,0.0,0.0,Muonon Stranbeate,True
8295,9253_01,Earth,True,G/1493/S,PSO J318.5-22,16.0,False,0.0,0.0,0.0,0.0,0.0,Jimmyn Thomason,True
8296,9254_01,Earth,True,G/1502/P,PSO J318.5-22,61.0,False,0.0,0.0,0.0,0.0,0.0,Kenny Mallerez,False
8297,9256_01,Earth,True,G/1494/S,TRAPPIST-1e,28.0,False,0.0,0.0,0.0,0.0,0.0,Darley Franton,True
8298,9257_01,Earth,False,F/1892/P,TRAPPIST-1e,13.0,False,39.0,0.0,1085.0,24.0,0.0,Ties Apple,False
8299,9259_01,Earth,False,F/1893/P,TRAPPIST-1e,44.0,False,1030.0,1015.0,0.0,11.0,0.0,Annah Gilleyons,True
8300,9261_01,Earth,True,G/1504/P,PSO J318.5-22,22.0,False,0.0,0.0,0.0,0.0,0.0,Therta Casentry,False
8301,9264_01,Europa,True,E/606/S,55 Cancri e,30.0,False,0.0,0.0,0.0,0.0,0.0,Giedir Sionerorly,True
8302,9267_01,Europa,True,E/607/S,TRAPPIST-1e,21.0,False,0.0,0.0,0.0,0.0,0.0,Arraid Opshaft,True
8303,9267_02,Europa,True,E/607/S,TRAPPIST-1e,20.0,False,0.0,0.0,0.0,0.0,0.0,Sabi Opshaft,True
8304,9268_01,Earth,True,G/1505/P,TRAPPIST-1e,31.0,False,0.0,0.0,0.0,0.0,0.0,Agnesa Baldson,True
8305,9270_01,Earth,True,G/1497/S,55 Cancri e,33.0,False,0.0,0.0,0.0,0.0,0.0,Lan Mckinsond,True
8306,9272_01,Earth,False,G/1507/P,TRAPPIST-1e,26.0,False,240.0,242.0,510.0,0.0,0.0,Ireene Simson,True
8307,9272_02,Earth,False,F/1894/P,TRAPPIST-1e,21.0,False,86.0,3.0,149.0,208.0,329.0,Gordo Simson,False
8308,9274_01,Europa,True,G/1508/P,TRAPPIST-1e,23.0,False,0.0,0.0,0.0,0.0,0.0,Chelsa Bullisey,True
8309,9275_01,Europa,False,A/97/P,TRAPPIST-1e,0.0,False,0.0,0.0,0.0,0.0,0.0,Polaton Conable,True
8310,9275_02,Europa,False,A/97/P,TRAPPIST-1e,32.0,False,1.0,1146.0,0.0,50.0,34.0,Diram Conable,False
8311,9275_03,Europa,False,A/97/P,TRAPPIST-1e,30.0,False,0.0,3208.0,0.0,2.0,330.0,Atlasym Conable,True
8312,9276_01,Europa,False,A/98/P,55 Cancri e,41.0,True,0.0,6819.0,0.0,1643.0,74.0,Gravior Noxnuther,False
8313,9278_01,Earth,True,G/1499/S,PSO J318.5-22,18.0,False,0.0,0.0,0.0,0.0,0.0,Kurta Mondalley,False
8314,9279_01,Earth,False,G/1500/S,TRAPPIST-1e,26.0,False,0.0,0.0,1872.0,1.0,0.0,Fayey Connon,True
8315,9280_01,Europa,False,E/608/S,55 Cancri e,32.0,False,0.0,1049.0,0.0,353.0,3235.0,Celeon Hontichre,False
8316,9280_02,Europa,False,E/608/S,TRAPPIST-1e,44.0,False,126.0,4688.0,0.0,0.0,12.0,Propsh Hontichre,True

In [97]:
# from sklearn.preprocessing import OneHotEncoder
# from sklearn.compose import make_column_transformer

# enc = OneHotEncoder()
# enc_df = pd.DataFrame(enc.fit_transform(space_data[['HomePlanet', 'Destination']]).toarray())
# enc_df.columns = enc.get_feature_names_out()
# train_df = space_data.join(enc_df)
# train_df.tail()

In [98]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
# label = le.fit(train_df[['', '', '']])

# train_df["CryoSleep_encoded"] = le.transform(train_df["CryoSleep"]) 
# train_df["VIP_encoded"] = le.transform(train_df["VIP"])
# train_df["Transported_encoded"] = le.transform(train_df["Transported"])
label = le.fit_transform(space_data['CryoSleep'])
label1 = le.fit_transform(space_data['VIP'])
label2 = le.fit_transform(space_data['Transported'])
label3 = le.fit_transform(space_data['HomePlanet'])
label4 = le.fit_transform(space_data['Destination'])

label[:5]
label1[:5]
label2[:5]

array([0, 1, 0, 0, 1], dtype=int64)

In [99]:
space_data.drop(['CryoSleep', 'VIP', 'Transported', 'HomePlanet', 'Destination', 'Name', 'PassengerId'], axis = 1, inplace = True)

space_data['CryoSleep'] = label
space_data['VIP'] = label1
space_data['Transported'] = label2
space_data['HomePlanet'] = label3
space_data['Destination'] = label4

In [100]:
space_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8317 entries, 0 to 8316
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Cabin         8317 non-null   object
 1   Age           8317 non-null   float64
 2   RoomService   8317 non-null   float64
 3   FoodCourt     8317 non-null   float64
 4   ShoppingMall  8317 non-null   float64
 5   Spa           8317 non-null   float64
 6   VRDeck        8317 non-null   float64
 7   CryoSleep     8317 non-null   int64
 8   VIP           8317 non-null   int64
 9   Transported   8317 non-null   int64
 10  HomePlanet    8317 non-null   int32
 11  Destination   8317 non-null   int32
dtypes: float64(6), int32(2), int64(3), object(1)
memory usage: 714.9+ KB

In [101]:
space_data[["CryoSleep", "VIP", "Transported", "HomePlanet", "Destination"]] = space_data[["CryoSleep", "VIP", "Transported", "HomePlanet", "Destination"]].astype(float)

In [102]:
space_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8317 entries, 0 to 8316
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Cabin         8317 non-null   object
 1   Age           8317 non-null   float64
 2   RoomService   8317 non-null   float64
 3   FoodCourt     8317 non-null   float64
 4   ShoppingMall  8317 non-null   float64
 5   Spa           8317 non-null   float64
 6   VRDeck        8317 non-null   float64
 7   CryoSleep     8317 non-null   float64
 8   VIP           8317 non-null   float64
 9   Transported   8317 non-null   float64
 10  HomePlanet    8317 non-null   float64
 11  Destination   8317 non-null   float64
dtypes: float64(11), object(1)
memory usage: 779.8+ KB

In [103]:
cabin_encoded = pd.get_dummies(space_data, columns=['Cabin'], sparse=True, dtype=int)
cabin_encoded.head()

# train_df = pd.concat([train_df, cabin_encoded], axis=1).reindex(train_df.index)
# train_df.drop('Cabin', axis=1, inplace=True)

,Age,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,CryoSleep,VIP,Transported,HomePlanet,...,Cabin_G/995/S,Cabin_G/996/S,Cabin_G/998/P,Cabin_G/998/S,Cabin_G/999/P,Cabin_G/999/S,Cabin_T/0/P,Cabin_T/1/P,Cabin_T/2/S,Cabin_T/3/P
0,39.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0,0,0,0,0,0,0,0,0,0
1,24.0,109.0,9.0,25.0,549.0,44.0,0.0,0.0,1.0,0.0,...,0,0,0,0,0,0,0,0,0,0
2,58.0,43.0,3576.0,0.0,6715.0,49.0,0.0,1.0,0.0,1.0,...,0,0,0,0,0,0,0,0,0,0
3,33.0,0.0,1283.0,371.0,3329.0,193.0,0.0,0.0,0.0,1.0,...,0,0,0,0,0,0,0,0,0,0
4,16.0,303.0,70.0,151.0,565.0,2.0,0.0,0.0,1.0,0.0,...,0,0,0,0,0,0,0,0,0,0

In [104]:
from sklearn.preprocessing import StandardScaler
num_cols = ["RoomService", "FoodCourt", "ShoppingMall", "Spa", "VRDeck"]

scaler = StandardScaler()
standardized_features = scaler.fit_transform(cabin_encoded[num_cols])

In [105]:
standardized_features[:5]

array([[-0.33246402, -0.28061788, -0.30705609, -0.26982037, -0.26643014],
       [-0.1680732 , -0.27499566, -0.26167324,  0.21740574, -0.22680192],
       [-0.2676126 ,  1.95327673, -0.30705609,  5.68960288, -0.22229871],
       [-0.33246402,  0.52086053,  0.36642539,  2.6845981 , -0.09260634],
       [ 0.12451228, -0.23688951, -0.03294368,  0.23160541, -0.26462886]])

In [106]:
# cabin_encoded.info(memory_usage='deep')
# memory_usage='deep'
cabin_encoded["RoomService"] = standardized_features[:, 0]
cabin_encoded["FoodCourt"] = standardized_features[:, 1]
cabin_encoded["ShoppingMall"] = standardized_features[:, 2]
cabin_encoded["Spa"] = standardized_features[:, 3]
cabin_encoded["VRDeck"] = standardized_features[:, 4]

In [107]:
# final_train = cabin_encoded[["household_size", "age_of_respondent", "year"]].values.astype(float
#     )
cabin_encoded.head()

,Age,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,CryoSleep,VIP,Transported,HomePlanet,...,Cabin_G/995/S,Cabin_G/996/S,Cabin_G/998/P,Cabin_G/998/S,Cabin_G/999/P,Cabin_G/999/S,Cabin_T/0/P,Cabin_T/1/P,Cabin_T/2/S,Cabin_T/3/P
0,39.0,-0.332464,-0.280618,-0.307056,-0.269820,-0.266430,0.0,0.0,0.0,1.0,...,0,0,0,0,0,0,0,0,0,0
1,24.0,-0.168073,-0.274996,-0.261673,0.217406,-0.226802,0.0,0.0,1.0,0.0,...,0,0,0,0,0,0,0,0,0,0
2,58.0,-0.267613,1.953277,-0.307056,5.689603,-0.222299,0.0,1.0,0.0,1.0,...,0,0,0,0,0,0,0,0,0,0
3,33.0,-0.332464,0.520861,0.366425,2.684598,-0.092606,0.0,0.0,0.0,1.0,...,0,0,0,0,0,0,0,0,0,0
4,16.0,0.124512,-0.236890,-0.032944,0.231605,-0.264629,0.0,0.0,1.0,0.0,...,0,0,0,0,0,0,0,0,0,0

In [108]:
# from scipy.sparse import lil_matrix
# import numpy as np

# def data_frame_to_scipy_sparse_matrix(df):
#     """
#     Converts a sparse pandas data frame to sparse scipy csr_matrix.
#     :param df: pandas data frame
#     :return: csr_matrix
#     """
#     arr = lil_matrix(df.shape, dtype=np.float32)
#     for i, col in enumerate(df.columns):
#         ix = df[col] != 0
#         arr[np.where(ix), i] = 1

#     return arr.tocsr()

# def get_csr_memory_usage(matrix):
#     mem = (X_csr.data.nbytes + X_csr.indptr.nbytes + X_csr.indices.nbytes) * BYTES_TO_MB_DIV
#     print("Memory usage is " + str(mem) + " MB")

# y_csr = y_sparse
# X_csr = data_frame_to_scipy_sparse_matrix(X_sparse)
# get_csr_memory_usage(X_csr)

## Prediction

In [109]:
from sklearn.decomposition import PCA, KernelPCA

kpca = KernelPCA(kernel="rbf", gamma=10, n_components=100)
features_kpca = kpca.fit_transform(cabin_encoded)

print("Reduced number of features:", features_kpca.shape[1])

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\validation.py:787: UserWarning: pandas.DataFrame with sparse columns found.It will be converted to a dense numpy array.
  warnings.warn(

Reduced number of features: 100

In [110]:
y_space_data = cabin_encoded['Transported']

In [111]:
y_space_data.shape

(8317,)

In [112]:
x_space_data = cabin_encoded.drop('Transported', axis=1)
x_space_data.shape

(8317, 6340)

In [114]:
# from sklearn.preprocessing import StandardScaler
# from sklearn.decomposition import TruncatedSVD
# from scipy.sparse import csr_matrix
# from sklearn import datasets
# import numpy as np

# # Make sparse matrix
# features_sparse = csr_matrix(x_space_data)
# # Create a TSVD
# tsvd = TruncatedSVD(n_components=600)
# # Conduct TSVD on sparse matrix
# features_sparse_tsvd = tsvd.fit(features_sparse).transform(features_sparse)
# # Show results
# print("Original number of features:", features_sparse.shape[1])
# print("Reduced number of features:", features_sparse_tsvd.shape[1])

In [115]:
from sklearn.model_selection import train_test_split
Xtrain, Xtest, ytrain, ytest = train_test_split(x_space_data, y_space_data, random_state=1)

In [116]:
# from sklearn.naive_bayes import GaussianNB, BernoulliNB
# from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegressionCV
# from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.neighbors import KNeighborsClassifier

# svc_linear = SVC(kernel="linear", random_state=0, C=1)
# svc_linear.fit(Xtrain, ytrain)
# y_model = svc_linear.predict(Xtest)
# model = LogisticRegressionCV()
# model = RandomForestClassifier(random_state=0, n_jobs=-1, class_weight="balanced")
model = AdaBoostClassifier(random_state=0)
# model= KNeighborsClassifier(n_neighbors=5, n_jobs=-1)
# model = DecisionTreeClassifier(random_state=0)
model.fit(Xtrain, ytrain)
y_model = model.predict(Xtest)

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\validation.py:787: UserWarning: pandas.DataFrame with sparse columns found.It will be converted to a dense numpy array.
  warnings.warn(
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\validation.py:787: UserWarning: pandas.DataFrame with sparse columns found.It will be converted to a dense numpy array.
  warnings.warn(

In [121]:
from sklearn.metrics import accuracy_score
accuracy_score(ytest, y_model)

0.7778846153846154